"""X-Files deals/needs schemas extracted from the monolith."""

from __future__ import annotations

from typing import Any, Dict, Optional

from app.schemas.compat_models import (
    XFilesContractMetricsDTO,
    XFilesContractTemplatesPageDTO,
    XFilesDailyContactsDTO,
    XFilesDealActionDTO,
    XFilesDealAssistantDTO,
    XFilesDealAuditPageDTO,
    XFilesDealContractKitDTO,
    XFilesDealContractStatusPayload,
    XFilesDealConversionDTO,
    XFilesDealDTO,
    XFilesDealOpportunitiesDTO,
    XFilesDealPatchPayload,
    XFilesDealPayload,
    XFilesDealRemindersDTO,
    XFilesDealsKanbanDTO,
    XFilesDealsPageDTO,
    XFilesDealsStatusDTO,
    XFilesEventSalesPlanDTO,
    XFilesNeedSignalsPageDTO,
    XFilesNegotiationBriefDTO,
    XFilesNorthStarDTO,
    XFilesOutreachSequenceActionDTO,
    XFilesProductMarginDTO,
    XFilesProductMarginPayload,
    XFilesProductMarginsPageDTO,
    XFilesProfitOptimizationDTO,
)

__all__ = [
    "Any",
    "Dict",
    "Optional",
    "XFilesContractMetricsDTO",
    "XFilesContractTemplatesPageDTO",
    "XFilesDailyContactsDTO",
    "XFilesDealActionDTO",
    "XFilesDealAssistantDTO",
    "XFilesDealAuditPageDTO",
    "XFilesDealContractKitDTO",
    "XFilesDealContractStatusPayload",
    "XFilesDealConversionDTO",
    "XFilesDealDTO",
    "XFilesDealOpportunitiesDTO",
    "XFilesDealPatchPayload",
    "XFilesDealPayload",
    "XFilesDealRemindersDTO",
    "XFilesDealsKanbanDTO",
    "XFilesDealsPageDTO",
    "XFilesDealsStatusDTO",
    "XFilesEventSalesPlanDTO",
    "XFilesNeedSignalsPageDTO",
    "XFilesNegotiationBriefDTO",
    "XFilesNorthStarDTO",
    "XFilesOutreachSequenceActionDTO",
    "XFilesProductMarginDTO",
    "XFilesProductMarginPayload",
    "XFilesProductMarginsPageDTO",
    "XFilesProfitOptimizationDTO",
]
